services:
  php:
    container_name: laravel-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-network
    depends_on:
      - mysql

  nginx:
    container_name: setup-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    networks:
      - setup-network
    depends_on:
      - php

  mysql:
    container_name: setup-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - setup-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - setup-network

  phpmyadmin:
    container_name: setup-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: setup-mysql
    networks:
      - setup-network
    depends_on:
      - mysql

  react:
    container_name: frontend-react
    build:
      context: ./docker/react
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - setup-network

networks:
  setup-network:
    driver: bridge

volumes:
  setup-data:
    driver: local